### ISSUE TITLE
Axiom Marketing Week 8 - 2/15

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#102]
Project: AX
Budget: 2.5hr

Please draft social media posts for the following blog articles:
https://medium.com/axiom-communications/when-social-media-becomes-a-tool-of-social-oppression-is-big-tech-accountable-fc6f3039ec62
https://medium.com/axiom-communications/the-american-referendum-on-women-in-leadership-639c4617f19a

Please upload the posts in the following google drive document for approval before release:
https://docs.google.com/spreadsheets/d/1j3So7RPgds_5uE3BCVzo2hYINBLhq3IAGSluibNkgYI/edit?usp=sharing

Also - is it possible to LINK BLOGS TO PHOTOS? We literally get 100x the number of photo clicks than link clicks. Look into it and let me know - thanks as always!

**Comment by kvsherrel** [comment]
Yeah so I figured it out, I can link the images to the blogs on facebook but the picture formating will be different, I was playing with it a little bit today. But I am having a hard time putting the images on the google doc, so maybe we can figure that out when we have our zoom meeting. Thanks girl!
