### ISSUE TITLE
RBG Blog - 3/13

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#111]
Project: AX
Budget: 1.5hr

Please draft an article for publication on Axiom's blog. Working title is "Mad Props to the RBG," and it's meant to be about all of the amazing things Ruth Bader Ginzburg has done for women (and all of us) over the years and how she deserves a ton of recognition and respect for her achievements. 
Tone is meant to be fun yet respectful, and I was thinking we should def showcase some of our own creative lingo. After all, William Shakespeare invented over 1700 common words - let's try to get at least like a dozen creative new slang words and phrases into the rotation ;-)
Here's 300 words to get you started, please expand to +/-1000 and add citations to reputable sources (footnotes in URL).
https://drive.google.com/file/d/1ni5bX3Tu1rD649t1RgSjIo0LHjDkj115/view?usp=sharing

**Comment by axiomcommunications** [comment]
Since today is international women's day, I'm finishing this project and posting it today.

**Comment by kvsherrel** [comment]
Oh your right that's a good idea, I'm sorry if I realized today was international woman's day I would have finished it yesterday. Sorry girl, let me know if you want help on this today.
