### ISSUE TITLE
Crypto Article Topic EXTRA 10/23

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#20]
Project: HALO
Budget: 1.5hr

Topic: Cryptocurrency-themed Halloween are costumes all the rage this year! Please develop an +/- 400 word article that describes the best of the best of cryptocurrency costumes this year.

**Comment by kvsherrel** [comment]
Would you like sources with this article?
Yes please!

**Comment by axiomcommunications** [comment]
Yes please do include sources - sorry for the omission!
No worries!
