### ISSUE TITLE
Update Axiom FB Page

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#27]
Project: AX
Budget: 1.5hr

Axiom hasn't had a FB presence - until now! Please fill out information on all forms on Axiom's FB page to make it as complete of a description of the company as possible. Please only use cut/paste from the website, but do so creatively (i.e. feel free to mix/match sentences). You can also use any corporate logos you may want (some are already up there) and any free commercial use images from www.pexels.com. All in all - make it sparkle, and have fun with it!

Once you've filled in all of the relevant information, please draft the first post. It's a share of an article that was recently published in a reasonably well-respected publication in hard copy. It's available here:
https://www.pabusinesscentral.com/pageview/viewer/2018-10-19#page=17
Please include actual image of the article and a one sentence explanation of the topic. Close congratulating me on the publication and tag my personal FB as well.

For the future, we will be posting regular content that cross-references back to the Axiom blog: https://medium.com/axiom-communications. This will be a following project that will be submitted on a bi-weekly basis.

When you accept this project please let me know and I'll add you as an admin. Thanks so much!

**Comment by kvsherrel** [comment]
Hey girl,  its been a while since you posted this so wanted to make sure you still want the first post on Axiom's page to be on the article above?

**Comment by axiomcommunications** [comment]
Yes please! Ultimately we want to promote all published materials, so might as well start with this one. Go ahead and post, and please also plan on getting another article shared before the weekend so we can start working through the backlog. I'll send materials shortly. Thanks!

**Comment by kvsherrel** [comment]
I'm pretty much done with this, except for one thing! The post only gives me the option to tag products and not people. I was wondering if you might be able to take a look and see if your able to tag someone in the actual post? Maybe its different because its a business page? If we can't in the actual post, should we tag you in the comments instead? Thanks girl!
