### ISSUE TITLE
Axiom Blog Kickoff

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#29]
Project: AX
Budget: $25 flat rate

Axiom is starting a long-overdue blog. Publications should be +/-400 words, with in-text hyperlinks as citations. One round of copyedits included, but your name will be published on the byline.

**Comment by kvsherrel** [comment]
Is there a general topic or tone you would like maintained in these blog articles?

**Comment by axiomcommunications** [comment]
Thanks for following up. All Axiom blogs can be on any topic of your
choosing, +/- 500 words, with citations as URLs. Please let me know what
topic you expect to write about before getting started, and we'll get these
posted in the next couple of weeks!
