### ISSUE TITLE
Industry PR - ASAP

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#34]
Project: TOP
Budget: 2hr

A client wants to expand reputation in their industry. They had a PR company create the linked article below. It features some of the industry leaders they want to highlight:

https://drive.google.com/file/d/1amGrKo-9cNu5ybD7mjU4UlKMrpDn9GNA/view?usp=sharing

This is an ongoing project (if we do a good job!) but we're starting with Paul Burleton. The topic is:  "76 reasons why you should be ready for article 76"
(start the post with: ok, not really 76 but…)

The piece should be heavily focused on the MiFID II/article 76 since that's what the guy is supposed to be an expert on. Please use his quotes in the article, but it's supposed to be an industry journalism piece not obvious marketing or PR. Consider taking a more academic tone. 
Thank you!

**Comment by kvsherrel** [comment]
This all sounds good, do you have a word count you would like me to aim for? And should  I start with Burleton and then include others? or should we primarily focus on him?

**Comment by axiomcommunications** [comment]
Word count on this one is  800-1000 words. Sorry for the omission, and
thanks so much for following up. And stick with Burleton - the idea is we
will be writing one of these for each of the others, so his is the test
run. Thanks again!

**Comment by axiomcommunications** [comment]
Wait - scratch that, word count is 600-800 - my bad :-P

**Comment by kvsherrel** [comment]
Haha, no worries! Sounds great!
