### ISSUE TITLE
Life Event Tax Summaries - 1/25

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#86]
Project: HT
Budget: 3HR

Tax client wants +/- 200 words on "Top # Tax Tips for People Who __________ This Year." Specifically:
1. Moved 
2. Bought a house
3. Sold a house
4. Owned rental property

Would you be able to draft +/- 200 words on each of the following by Friday 1/25? No citations necessary, these are informational social media posts. Let me know, and thanks as always!

**Comment by kvsherrel** [comment]
Yes, I sure can!
