### ISSUE TITLE
SAT Writing Passages 1/25

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#90]
Project: SAT
Budget: 4HR

Please prepare four (4) +/-300 word descriptions on topics of your choosing that fall within each of the following categories:

1. a biography of a person who made an important contribution or accomplishment,

2. an important technological achievement,

3. an event that changed the course of history, and
 
4. applied health/science.

Since these are educational materials prepared to drill advanced editing and grammatical concepts, each submission must follow a clear progression with (1) an introductory paragraph, (2) 2-3 body paragraphs, and (3) a clear conclusion. Please follow the style of SAT samples in prep book and PDF, and please let me know if you have any questions. 

The deadline for this will be FRIDAY, 1/25 @ NOON.

THANK YOU!!!!!

**Comment by kvsherrel** [comment]
Hey girl! quick question, sorry I just noticed this! Are you referring to the PDF in the SAT reading sample? or should there be a PDF attached?

**Comment by axiomcommunications** [comment]
Hey!
   No, just the writing section of the SAT PDF you used to draft the
reading questions, and whatever is in the book you got from the library (if
you still have it). Here's one I've done as a sample - sorry for the delay!
