### ISSUE TITLE
M&A kickoff - 2/9

### ISSUE THREAD

**Issue by kvsherrel** [axiomcommunications/Project-Management#94]
Project: M&A
Budget: 4.5HR

Please draft two (2) +/- 1000 word articles on topics of real estate transactions: (1) “What is a Short Sale?" and (2) “Short Sale vs Foreclosure”.
This is a blog for a law firm, so it should be supported by citations to applicable laws and other reliable sources to ensure legitimacy and authority.  Please also use the phrase "short sale" as much as possible for SEO.

**Comment by axiomcommunications** [comment]
https://malawillinois.com <- Client

**Comment by axiomcommunications** [comment]
If you need an extra day on this let me know - thanks as always!

**Comment by kvsherrel** [comment]
Thanks girl, an extension would be nice! I will probably still turn it in before Saturday but I just came down with a cold, so I'm crossing my fingers in hopes that it doesn't last!
