### ISSUE TITLE
Tax Course - 3/12

### ISSUE THREAD

**Issue by axiomcommunications** [axiomcommunications/Project-Management#95]
Project: NPC
Budget: 10HR

Please draft an annotated research outline for the State and Local Tax (SALT) course. The course has five modules, and the general content outline is available here:
https://drive.google.com/file/d/19dVchFuhFsm6i1J3qB1UQC-OvldgGR2f/view?usp=sharing

This is an academic project requiring research and citation to original sources. You will be filling out the outline provided with content footnoted to reliable citations. Look for materials from the American Bar Association and academic journals available without paywalls, as well as professional publications (i.e. Tax Policy Institute). Avoid journalistic sources, and cite to original source law (statutes, regulations, and case law) where you can. Because this is an outline, narrative is not important - just looking for content supported by quality citations.

**Comment by kvsherrel** [comment]
Hey Sam, I had a quick question. Under #1 Tax powers - Under Supreme Court Case Law - I was wondering if you could provide a little information on what you would like me to include on that subject? When I use a search engine I just get a bunch of recent cases from the Supreme Court. I think I know what you're looking for but I want to make sure I'm on the same page as you.

**Comment by axiomcommunications** [comment]
Sure thing girl! Basically, any current SCOTUS cases focusing on the tax
and spend clause in the constitution, or the state's tax powers reserved
under the 10th amendment. Here's a reference on the state side to get you
started (it links to the actual case):
https://taxfoundation.org/limits-state-tax-powers-modest-reply-justice-scalia/
as well as the federal side:
https://www.dailysignal.com/2012/06/29/whats-the-limit-on-congresss-power-to-tax/
Although I didn't include it in the outline, we should DEFINITELY include
whatever case law came down following the Supreme Court review of
Obamacare, since the healthcare law was actually passed under federal tax
authority. Thanks as always, and let me know if you have any more questions!

**Comment by kvsherrel** [comment]
Hey love, I was wondering if you had an example for # 2 under: Activities subject to state and federal oversight? I'm just wondering if you wanted me to list things like agricultural oversight, oversight on mortgages, stuff like that? Or if you had some activities in mind?  I know you had activities listed under Activities common regulating locally - so I thought I should ask! 

Thanks girl!

**Comment by axiomcommunications** [comment]
Hey girl!
   Sorry for the late reply on this - my sister just left and I'm just now
getting back to things. Basically, licenses are types of indirect taxes, so
this section is just about the types of activities people can expect to
have to get a license for. Not general stuff like driving a car or owning a
gun or anything like that, but like how some states/cities require business
licenses, food handling licenses, licensing for certain professional
activities like plumbing or electrical or whatever - stuff like that. Does
that make sense?
Thanks love!
Sam

**Comment by kvsherrel** [comment]
Thank you girl! That really clears things up for me!

**Comment by axiomcommunications** [comment]
Hey! here are some resources that may be helpful as you finalize the outlines: https://www.americanpayroll.org/education-certification/courses-seminars/compliance-education/state-and-local

https://www.bdo.com/insights/tax/state-and-local-tax/state-and-local-tax-issues-presented-by-federal-ta

https://www.taxpolicycenter.org/briefing-book/how-do-state-and-local-property-taxes-work

http://www.ncsl.org/documents/fiscal/statefederalandlocaltaxes.pdf
